[package]
name = "os_tsukurundamon"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# 我々のOSではアンワインドを使用したくないのでpanic='abort'で無効化する。
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"